name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y libxml2-dev
    - uses: abel0b/setup-premake@v2.4
      with:
        version: "5.0.0-beta2"
    - name: build
      run: bash scripts/build.sh release
    - uses: actions/upload-artifact@v4
      with:
        name: anido
        path: bin/release/anido
